name = "fiverr-promo-website"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = ".vercel/output/static"

# Build command
[build]
command = "npm run pages:build"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "fiverr-articles"
database_id = "your-database-id-here"

# Environment variables (optional)
[vars]
NODE_ENV = "production"


